#!/usr/bin/env python

from intermittent_monitoring.monitor_fmeasure import *

if __name__ == '__main__':
    area = 3
    fmeasure_listener = FMeasureListener(area=area, sleep=5)
    filename = 'random_fmeasure' + str(area) + '.pkl'
    print("Listening to F-measure: Area " + str(area))
    result = fmeasure_listener.save_recorded_array(t_operation=100, filename=filename)
    print("Stored fmeasure data:", result)
    #rospy.spin()