#!/usr/bin/env python

import rospy
from intermittent_monitoring.monitor_fmeasure import *

if __name__ == '__main__':

    fmeasure_listener = FMeasureListener(area=1, sleep=10)
    filepath = 'intermittent_monitoring/results/random_fmeasure1.pkl'
    result = fmeasure_listener.save_recorded_array(t_operation=1000, filename=filepath)
    print("Stored fmeasure data:", result)
    #rospy.spin()